export enum EventType {
  RFI = 'RFI',
  RFP = 'RFP',
  RFQ = 'RFQ',
  ITT = 'ITT',
  PQ = 'PQ',
  REVERSE_AUCTION = 'REVERSE_AUCTION',
  DUTCH_AUCTION = 'DUTCH_AUCTION',
  JAPANESE_AUCTION = 'JAPANESE_AUCTION',
}

export enum EnvelopeStructure {
  SINGLE = 'SINGLE',
  DOUBLE = 'DOUBLE',
  THREE_ENVELOPE = 'THREE_ENVELOPE',
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  AUCTION_OPEN = 'AUCTION_OPEN',
  CLOSED = 'CLOSED',
  IN_EVALUATION = 'IN_EVALUATION',
  AWARDED = 'AWARDED',
  CANCELLED = 'CANCELLED',
}

export enum AuctionType {
  ENGLISH = 'ENGLISH',
  RED_LIGHT = 'RED_LIGHT',
  DUTCH = 'DUTCH',
  JAPANESE = 'JAPANESE',
  RANK_ONLY = 'RANK_ONLY',
  RANK_WITH_WINNING_BID = 'RANK_WITH_WINNING_BID',
  GENERIC_ALLIANCE = 'GENERIC_ALLIANCE',
  UNIQUE_ALLIANCE = 'UNIQUE_ALLIANCE',
  VICKREY = 'VICKREY',
  MULTI_ATTRIBUTE = 'MULTI_ATTRIBUTE',
}

export enum AuctionStatus {
  CONFIGURED = 'CONFIGURED',
  PREVIEW = 'PREVIEW',
  LIVE = 'LIVE',
  EXTENDED = 'EXTENDED',
  BAFO = 'BAFO',
  CLOSED = 'CLOSED',
}

export enum AwardMode {
  WHOLE_EVENT = 'WHOLE_EVENT',
  LOT_LEVEL = 'LOT_LEVEL',
  LINE_LEVEL = 'LINE_LEVEL',
  SPLIT = 'SPLIT',
  CONDITIONAL = 'CONDITIONAL',
}

export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  BU_HEAD = 'BU_HEAD',
  EVENT_MANAGER = 'EVENT_MANAGER',
  EVALUATOR = 'EVALUATOR',
  OBSERVER = 'OBSERVER',
  SUPPLIER = 'SUPPLIER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  LOCKED = 'LOCKED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum Permission {
  // Organisation
  ORG_CREATE = 'ORG_CREATE',
  ORG_UPDATE = 'ORG_UPDATE',
  ORG_VIEW = 'ORG_VIEW',
  // Business Unit
  BU_CREATE = 'BU_CREATE',
  BU_UPDATE = 'BU_UPDATE',
  BU_VIEW = 'BU_VIEW',
  // Users
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_VIEW = 'USER_VIEW',
  USER_ASSIGN_ROLE = 'USER_ASSIGN_ROLE',
  USER_IMPERSONATE = 'USER_IMPERSONATE',
  // Events
  EVENT_CREATE = 'EVENT_CREATE',
  EVENT_UPDATE = 'EVENT_UPDATE',
  EVENT_VIEW = 'EVENT_VIEW',
  EVENT_PUBLISH = 'EVENT_PUBLISH',
  EVENT_DELETE = 'EVENT_DELETE',
  // Auctions
  AUCTION_CREATE = 'AUCTION_CREATE',
  AUCTION_START = 'AUCTION_START',
  AUCTION_CLOSE = 'AUCTION_CLOSE',
  AUCTION_VIEW = 'AUCTION_VIEW',
  // Bids
  BID_SUBMIT = 'BID_SUBMIT',
  BID_VIEW_OWN = 'BID_VIEW_OWN',
  BID_VIEW_ALL = 'BID_VIEW_ALL',
  // Evaluation
  EVAL_SCORE = 'EVAL_SCORE',
  EVAL_VIEW = 'EVAL_VIEW',
  EVAL_MANAGE = 'EVAL_MANAGE',
  // Award
  AWARD_RECOMMEND = 'AWARD_RECOMMEND',
  AWARD_APPROVE = 'AWARD_APPROVE',
  AWARD_VIEW = 'AWARD_VIEW',
  // Contracts
  CONTRACT_CREATE = 'CONTRACT_CREATE',
  CONTRACT_VIEW = 'CONTRACT_VIEW',
  CONTRACT_SIGN = 'CONTRACT_SIGN',
  // Suppliers
  SUPPLIER_VIEW = 'SUPPLIER_VIEW',
  SUPPLIER_MANAGE = 'SUPPLIER_MANAGE',
  // Analytics
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
  // Admin
  ADMIN_SETTINGS = 'ADMIN_SETTINGS',
  ADMIN_AUDIT_LOG = 'ADMIN_AUDIT_LOG',
}
